### ISSUE TITLE
Archivate.sh shuts down itself

### ISSUE THREAD

**Issue by naziko2411** [naer2/instagramStoryDownloader#11]
Hey there. I've just downloaded instagramStoryDownloader. My problem is that Archivate.sh or some files shut down itself. Help me for the files not shutting down, or is there a way for not shutting down itself?

**Comment by naer2** [comment]
Do you have any error message?

**Comment by naziko2411** [comment]
Yes. I've opened shell /usr/bin/bash login, but I've after opened it, there is an error message:
bash: test.txt: Permission denied,
find: './downloaded': No such file or directory
bash: test.txt: No such file or directory.
After seeing this message, the script shut down itself. Are there ways to solve this problem? :(

**Comment by naer2** [comment]
Can you try with sudo?

**Comment by naziko2411** [comment]
Oh, with sudo? Haven't tried it yet.

**Comment by naziko2411** [comment]
And How to install sudo?

**Comment by naer2** [comment]
I think you don't have permission to create folder but i don't sure. Just type sudo php index.php and try.

**Comment by naziko2411** [comment]
Hmm… I am a quite noob to write these scripts and I don't really know how I install PHP although I am experiencing in project. And I will start to use this script in August, and my mission is that to download files in PHP scripts.

**Comment by naer2** [comment]
I think you want to download celebreties story's. That script clearly working fine rn.

**Comment by naziko2411** [comment]
Yeah, every user.

**Comment by naer2** [comment]
Any other problem you can contact me via telegram.

**Comment by naziko2411** [comment]
I don't use Telegram that much, but I have to try PHP probably tomorrow, thanks. I really want to use this script with functions.

**Comment by naziko2411** [comment]
So how do the functions work for each user?

**Comment by naziko2411** [comment]
Another question: Is this script's files limited or opposite?

**Comment by naer2** [comment]
@afwn90cj93201nixr2e1re

**Comment by naziko2411** [comment]
Thanks for shel's advice.

**Comment by afwn90cj93201nixr2e1re** [comment]
At first you should be inside directory for running Archivate.sh, error's says that: 
```
bash: test.txt: Permission denied,
find: './downloaded': No such file or directory
bash: test.txt: No such file or directory.
```
Second one, try to execute `chmod -R 777 *` while you inside folder, execute it once, until you have changed .sh file.
Third one errors says that possible you download dir isn't exists, that's why txt file, which contains dates for archiving doesn't exists. You should show `ls` output inside dir.

**Comment by naziko2411** [comment]
Thanks, although my computer is Windows 10, how should I execute chmod -R 777 in Windows 10?
