### ISSUE TITLE
Don't know how I install it

### ISSUE THREAD

**Issue by naziko2411** [naer2/instagramStoryDownloader#12]
Hey there. I may asking too many questions in this project, I am starting to use this project this month, but I'm not sure how I install this since I'm aware to see celebs' IG stories. And Mgp25 API was gone as I first saw this project. Help me how I install this project, please.

**Comment by naer2** [comment]
What you mean with install?

**Comment by naziko2411** [comment]
With Git, CMD, RStudio or whatever. I am newbie or noob at installing and cloning Github repos and PHPstorm is not opening my Windows computer, so this is for help.

**Comment by naer2** [comment]
@afwn90cj93201nixr2e1re

**Comment by afwn90cj93201nixr2e1re** [comment]
Em.
```
git clone https://github.com/naer2/instagramStoryDownloader
cd instagramStoryDownloader
php -f index.php
```
??

**Comment by naziko2411** [comment]
How did it work?

**Comment by naer2** [comment]
Just write this codes to terminal.

**Comment by naziko2411** [comment]
Does Windows Terminal really work with it?

**Comment by naer2** [comment]
Bro, do you know Turkish?

**Comment by naziko2411** [comment]
Yes.

**Comment by naer2** [comment]
Tek yapman gereken kodlari indirip config.php'de kullanici adi ve sifreni girdikten sonra terminal'de index.php'yi calistirmak. Gayet stabil bir sekilde calisiyor. Bir sorunun olursa tekrar sorabilirsin.
