### ISSUE TITLE
Usage of functions.php

### ISSUE THREAD

**Issue by naziko2411** [naer2/instagramStoryDownloader#13]
Although, I am interested in functions.php, but where can I open it?

**Comment by naer2** [comment]
function.php'de bir seyi degistirmene gerek yok. Kullandigin editorle acabilirsin Atom'u oneririm bunun icin.

**Comment by naziko2411** [comment]
Yardiminiz için teşekkürler. Yine takıldığım zaman yine sorular sorarım :)
.
