### ISSUE TITLE
How can get story time and the mentions in the story ?

### ISSUE THREAD

**Issue by tawfek** [naer2/instagramStoryDownloader#2]
How can get story time and the mentions in the story ?
i tried too many times and see the wikis of mgp25 but i did not found how to use it 
can any one tell me how to get story time and the users that been mentioned inside  the story ?

**Comment by tawfek** [comment]
get story time issue solved :
$storyFeed->getReel()->getItems()[0]->getTakenAt()
still trying to get the usernames mention in the story 
and trying to get instagram story highlight

**Comment by naer2** [comment]
Thanks for your update. I will look about story mention.

**Comment by tawfek** [comment]
thank you for fast replying  i want to ask you some thing ...
i made full react front end modern design for instagram stories downloader  
and i fetched stories from instagram using mgp25 script but i can not fetch too many stories because the limitation ... so do you know how to fetch too many stories without getting warning about limiting is there any way to across this problem :( ??

**Comment by naer2** [comment]
I think it's about Instagram API. I want to see your design for ISD. You can contact me via Telegram with same username.
